# Generated by Django 3.0.5 on 2020-04-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_merchantcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='merchant_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descmcc', to='categories.MerchantCode'),
        ),
    ]
