# Generated by Django 3.0.5 on 2020-04-20 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('owner', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=32)),
                ('operation_sum', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bargain_sum', models.DecimalField(decimal_places=2, max_digits=18)),
                ('comment', models.CharField(max_length=128)),
                ('import_date', models.DateField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='operations.Account')),
                ('bargain_cur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bargain_cur', to='categories.Currency')),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description', to='categories.Description')),
                ('merchant_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcc', to='categories.MerchantCode')),
                ('operation_cur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_cur', to='categories.Currency')),
            ],
        ),
    ]
