# Generated by Django 3.0.5 on 2020-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20200430_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
