# Generated by Django 3.0.5 on 2020-05-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200421_2315'),
        ('operations', '0004_auto_20200502_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='merchant_code_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mcc_orig', to='categories.MerchantCode'),
        ),
    ]
