# Generated by Django 3.0.5 on 2020-05-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_operation_merchant_code_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
